In [ ]:
# Numpy --> Numerical Python
import numpy as np
print(np.__version__)


2.0.2


In [ ]:
# numpy provides the support for most powerful data structure -- array
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr)
print(type(arr))

[10 20 30 40 50 60]
<class 'numpy.ndarray'>


In [ ]:
# Python List vs Numpy
list1 = [10,20,30,40,50,60]
total = 0
for i in list1:
    total = total + i   # total = 0 + 10
print(total)

210


In [ ]:
list1 = [10,20,30,40,50,60]
print(sum(list1))

210


In [ ]:
arr = np.array([10,20,30,40,50,60])
print(np.sum(arr))

210


In [ ]:
# Python List vs Numpy

# how much execution time will be taken by List and sum()
import time
numbers = list(range(1,1001))
total = 0
start_time = time.time()  # record start time
for i in numbers:
  total = total + i
end_time = time.time()  # record end time
print("Total : ",total)
print("Execution Time : ",end_time - start_time,"seconds")
print(f"Execution Time : {end_time - start_time:.4f} seconds")
#.4f means show 4 digits after the decimal point

Total :  500500
Execution Time :  0.0004436969757080078 seconds
Execution Time : 0.0004 seconds


In [ ]:
import numpy as np
import time
numbers = np.arange(1,1000000001)
total = 0
start_time = time.time()  # record start time
total = np.sum(numbers)
end_time = time.time()  # record end time
print("Total : ",total)
print("Execution Time : ",end_time - start_time,"seconds")
print(f"Execution Time : {end_time - start_time:.4f} seconds")

Total :  500000000500000000
Execution Time :  1.2253735065460205 seconds
Execution Time : 1.2254 seconds


In [ ]:
# array()
# In programming, an array is a data structure used to store collection of data values

# Array : Single Dimension (1D) and Multi Dimensional (2D)

# How to create an aaray (1D)
arr = np.array([10,20,30,40,50,60])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40 50 60]


In [ ]:
# An array is a collection of Similar Data Type
emp_info = np.array([123, 'Beez' , 89.11 , True])
print(emp_info)

['123' 'Beez' '89.11' 'True']


In [ ]:
# shape property
# used to determine the dimensions of an array
# For 1D array return (n,) --> where n is the number of elements
# For 2D array return (n,m) --> where n is the number of rows and m is the number of columns

arr = np.array([10,20,30,40,50,60])
print(arr.shape)

(6,)


In [ ]:
# 2D Array
arr = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(arr.shape)
print(arr)

# Tips for 2D Array
# np.array([])
# 3x3 matrix

# 2x5 Matrix
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)
print(arr)

# 4x3 Matrix
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr.shape)
print(arr)

(3, 3)
[[1 2 3]
 [3 4 5]
 [5 6 7]]
(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Indexing And Slicing
arr = np.array([10,20,30,40,50,60])

# 10  20  30  40  50  60
# 0   1   2   3   4   5
#-6  -5  -4  -3  -2  -1

print(arr)
print(arr[-1])
print(arr[3])
print(arr[1:5])
print(arr[::-1])

[10 20 30 40 50 60]
60
40
[20 30 40 50]
[60 50 40 30 20 10]


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[1,1])   # show me the element which exist at r1 and c1
print(arr[2,2])

# show me the first row only
print(arr[0])

# show me the second column only   FOR COLUMNS USE THIS SYNTAX [:,COLUMN_INDEX_NUMBER]
print(arr[:1])
print(arr[:,2])

print(arr[2])

# show only first 2 rows
print(arr[0:2])      # ROW 0 AND ROW 1

print(arr[:,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
9
[1 2 3]
[[1 2 3]]
[3 6 9]
[7 8 9]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]


In [ ]:
# Numpy Data Types
arr = np.array([10,20,30,40])
print(arr.dtype)
# dtype property helps us to determine the data type of an Array

int64


In [ ]:
arr = np.array([10.1,20.2,30.3,40.4])
print(arr.dtype)

float64


In [ ]:
arr = np.array([True,False,False,True])
print(arr.dtype)

bool


In [ ]:
arr = np.array(['A','B','C'])
print(arr.dtype)

<U1


In [ ]:
arr = np.array(['Python','Nextperts Academy','A','B'])
print(arr.dtype)

<U17


In [ ]:
# we can also use dtype for Conversion
arr = np.array([10,20,30,40])
print(arr.dtype)
print(arr.nbytes)  # total bytes used by an array

# this int64 means 64 Bits
# meaning each and every individual element of an array can take upto 64 bits
# we have 4 elements
# 4 * 64 Bits --> Total Size of Arr : 256 bits
# and if we convert it into bytes 4 elements * 8 bytes : 32 bytes

# behind the scene each and every individual element will gonna take 64 digits space

# 6bits 6*4 ==> 24 bits
#  Total Size Of Arr :24 bits

int64
32


In [ ]:
arr = np.array([10,20,30,40],dtype='i1')
print(arr.dtype)
print(arr.nbytes)

# this int8 means 8 Bits
# meaning each and every individual element of an array can take upto 8 bits
# we have 4 elements
# 4 * 8 Bits --> Total Size Of Arr : 32 bits
# and if we convert it into bytes  4 element * 1 bytes  : 4 bytes

# behind the scene each and every individual element will gonna take 8 digits space


# when in an array you are storing the age or marks

int8
4


In [ ]:
age = np.array([34,78,56,21,90,100,120,17])
print(age.dtype)

int64


In [ ]:
age = np.array([34,78,56,21,90,100,120,17],dtype='i1')
print(age.dtype)
print(age.nbytes)

int8
8


In [ ]:
age = np.array([34,78,56,21,90,100,120,17],dtype='i4')
print(age.dtype)
print(age.nbytes)

# i1 --> 8 digits space
# i2 --> 16 digits space
# i4 --> 32 digits space
# i8 --> 64 digits space

int32
32


In [ ]:
a = np.array([10,20,30,40,50],dtype='f')
print(a)
print(a.dtype)

[10. 20. 30. 40. 50.]
float32


In [ ]:
a = np.array([10., 20., 30., 40., 50.,],dtype='i')
print(a)
print(a.dtype)

[10 20 30 40 50]
int32


In [ ]:
# astype() used for conversions
arr = np.array([10., 20., 30., 40., 50.,])
arr = arr.astype('i8')
print(arr.dtype)

int64


In [ ]:
# copy() vs view() methods of numpy

# copy()
# a copy will create a new independent array in a different memory location

org_array = np.array([1,2,3,4,5,6])
print(org_array)

copied_arr = org_array.copy()
print(copied_arr)

# if we make any changes in copied array, it won't effect the original array
copied_arr[0] = 100
print(copied_arr)
print(org_array)

# if we make any changes in org array, it will effect the copied array
org_array[4] = 400
print(org_array)
print(copied_arr)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[100   2   3   4   5   6]
[1 2 3 4 5 6]
[  1   2   3   4 400   6]
[100   2   3   4   5   6]


In [ ]:
org_array = np.array([1,2,3,4,5,6])
copied_arr = org_array.view()

# shares_memory() --> return True if arrays are sharing the same memory location

print(np.shares_memory(org_array,copied_arr))

True


In [ ]:
# Numpy Array Reshaping
# Converting 1D into 2D or Converting 2D into 1D
# reshape()

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape) # 2x6  3x4  4x3  6x2  12x1  1x12

arr = arr.reshape(3,4)
print(arr)
print(arr.shape)

(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [ ]:
# numpy.newaxis is used to increase the dimension of the existing array by one more dimension
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
# arr[:,np.newaxis]            Column Vector
arr = arr[np.newaxis,:]      # Row Vector
print(arr.shape)

(1, 13)


In [ ]:
# Converting 2D into 1D
# Option 1
twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)

arr = twod.reshape(6)  #or (-1)
print(arr)

(3, 2)
[1 2 3 4 5 6]


In [ ]:
# Option 2
twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)

arr = twod.reshape(-1)
print(arr)

(3, 2)
[1 2 3 4 5 6]


In [ ]:
# Option 3
twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)

arr = twod.flatten()
print(arr)

(3, 2)
[1 2 3 4 5 6]


In [ ]:
# concatenate()
# used to join 2 arrays

pp1 = np.array([20,60,80,45,32])
pp2 = np.array([10,20,30,40,50,67,32,90])
pp3 = np.array([100,200,300,400])
arr = np.concatenate((pp1,pp2,pp3))
print(arr)

[ 20  60  80  45  32  10  20  30  40  50  67  32  90 100 200 300 400]


In [ ]:
t1 = np.array([[1,2],[3,4]])
t2 = np.array([[5,6],[7,8],[9,10]])
arr = np.concatenate((t1,t2))
print(arr)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
# array_split()
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
arr = np.array_split(arr,3)
print(arr[0])
print(arr[1])
print(arr[2])

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [ ]:
# Sorting
# np.sort() by default it will sort in an ascending order

prices = np.array([78,34,56,90,102,34,12,67,172,120,95,40])
print(np.sort(prices))

[ 12  34  34  40  56  67  78  90  95 102 120 172]


In [ ]:
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,40])
print(np.sort(prices)[::-1])  # descending order

[172 120 102  95  90  78  67  56  40  34  34  12]


In [ ]:
# Filter and Searching In An Array
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
print(prices)

for i in prices:
  if i>=50:
    print(i)

[ 78  34  56  90 102  34  12  67 172 120  95  45]
78
56
90
102
67
172
120
95


In [ ]:
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
# Boolean Masking
prices>=50

array([ True, False,  True,  True,  True, False, False,  True,  True,
        True,  True, False])

In [ ]:
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
# Boolean Masking
newarr = prices[prices>=50]
print(newarr)

[ 78  56  90 102  67 172 120  95]


In [ ]:
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
# show the even number prices
even = prices[prices%2==0]
print(even)

[ 78  34  56  90 102  34  12 172 120]


In [ ]:
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
# np.where(expression)
# np.where returs INDEX NUMBERS
res = np.where(prices%2==0)
print(prices[res])

[ 78  34  56  90 102  34  12 172 120]


In [ ]:
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
res = np.where((prices%2==0) & (prices>=50))
print(prices[res])

# & combines both conditions

[ 78  56  90 102 172 120]


In [ ]:
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
print(prices[(prices%2==0) & (prices>=50)])

[ 78  56  90 102 172 120]


In [ ]:
# SALARY CLASSIFICATION
salary = np.array([25000, 40000, 55000, 70000, 30000, 90000])
# Replace salary with High if salary >=60000
# Replace salary with Medium if salary >=40000 and <=60000
# Otherwise Low

# np.where(condition,valur_if_true,value_if_false)

result = np.where(
    salary >= 60000, 'High',
    np.where(salary >=40000, 'Medium' , 'Low')
)

print(result)

['Low' 'Medium' 'Medium' 'High' 'Low' 'High']


In [ ]:
# Numpy Random Module
from numpy import random
x = random.randint(100)  # 1 till 100
print(x)

16


In [ ]:
x = random.randint(100,150)  # 100 till 150
print(x)

102


In [ ]:
# rand() generate random float
# method returns a random float value between 0 and 1

print(random.rand())

0.384360387311382


In [ ]:
# generating 1D Array
arr = random.randint(30,120,size=(5)) # size means dimensions of an array
print(arr)

[ 36  77 119  86  35]


In [ ]:
# generating 2D Array
arr = random.randint(30,120,size=(3,4)) # size means dimensions of an array
print(arr)

[[108  85  59  63]
 [ 31  66  87  62]
 [ 67  90 118 105]]


In [ ]:
arr = random.rand(10)
print(arr)

[0.04106287 0.10590449 0.711033   0.20319916 0.18645621 0.6746552
 0.07151311 0.90145495 0.63319086 0.26316262]


In [ ]:
arr = random.rand(5,4)
print(arr)

[[0.938582   0.48090026 0.01686956 0.21614982]
 [0.68095819 0.88107659 0.59320388 0.67233237]
 [0.17281273 0.15673811 0.89337778 0.86104188]
 [0.92397898 0.26140134 0.98730291 0.36329676]
 [0.98266849 0.95306515 0.02079038 0.08580476]]


In [ ]:
# choice() method allows you to generate a random value
# based on an array of values

arr = random.choice([10,20,30,40,50,60])
print(arr)

60


In [ ]:
arr = random.choice([10,20,30,40,50,60],size=(7))
print(arr)

[50 20 10 10 30 30 40]


In [ ]:
arr = random.choice([10,20,30,40,50,60],size=(3,4))
print(arr)

[[20 60 10 50]
 [10 10 20 20]
 [40 60 10 60]]


In [ ]:
# numpy.zeros()
# this function allows us to create an array filled with Zeros
# default data type will be Float

x = np.zeros(7)
print(x)

[0. 0. 0. 0. 0. 0. 0.]


In [ ]:
x = np.zeros((3,3),dtype=i)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# numpy.ones()
# this function allows us to create an array filled with Oned
# default data type will be Float

x = np.ones(7)
print(x)

[1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# numpy.sum()
# used to compute the sum of all elements

x = np.random.randint(50,size=(120))
print(x)
print(np.sum(x))

[ 6 34 20 41 15 14 40 29 39 33 34 36 28 46  5 16 27 24 35 41  6 12 40 32
  0 15 19 37 26  6 11  8 49 43 31 21 29 45 44  4 14 35 38 43 32  1  1 20
  4 35 35 17  8 13  0 39 42 39  8  4 27  0 11 25 47 19 39 49 18 17 49 16
 49 46 39 35 11 37 24 14 47 12 38 18 22 11 16 31 49 14 37 41 34 24 16 46
 25  5 39 29 42 38  9 41 11 44  0 43 14 25  7 31 10  8 33 15 27 43 39 49]
3124


In [ ]:
print('Sum of An Array')
print(np.sum(x))

Sum of An Array
3124


In [ ]:
# numpy.mean()
# mean value is the average value
print('Mean of An Array')
print(np.mean(x))

Mean of An Array
26.033333333333335


In [ ]:
print('Min of An Array')
print(np.min(x))
print('Max od An Array')
print(np.max(x))

Min of An Array
0
Max od An Array
49


In [ ]:
# numpy.unique()
# return unique elements as a sorted array
a = np.array([1,2,3,11,4,10,9,12,5,6,1,4,3,2,5,6,7,8,9,2,3,4,5,7,1])  # remove duplicated numbers
print(np.unique(a))

# 1 2 3 11 4 10 9 12 5 6 7 8

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
a = np.array([1,2,3,11,4,10,9,12,5,6,1,4,3,2,5,6,7,8,9,2,3,4,5,7,1])
np.unique(a,return_index=True)

# return_index  --> it will print the index numbers

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 0,  1,  2,  4,  8,  9, 16, 17,  6,  5,  3,  7]))

In [ ]:
a = np.array([1,2,3,11,4,10,9,12,5,6,1,4,3,2,5,6,7,8,9,2,3,4,5,7,1])
uv , i = np.unique(a,return_index=True)
print(uv)
print(i)
# return_index   --> it will print the index numbers

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  1  2  4  8  9 16 17  6  5  3  7]


In [ ]:
# argsort --> reorder the index numbers in a proper sequence
uv[np.argsort(i)]

array([ 1,  2,  3, 11,  4, 10,  9, 12,  5,  6,  7,  8])

In [ ]:
a = np.array([1,2,3,11,4,10,9,12,5,6,1,4,3,2,5,6,7,8,9,2,3,4,5,7,1])
uv , i = np.unique(a,return_index=True)
uv[np.argsort(i)]

array([ 1,  2,  3, 11,  4, 10,  9, 12,  5,  6,  7,  8])

In [ ]:
# arange()
print(np.arange(10))
print(np.arange(1,11))
print(np.arange(1,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [ ]:
# Numpy Broadcasting
arr1 = np.array([16,24,26])
arr2 = np.array([13,22,19])
print(arr1+arr2)
print(arr1*arr2)

[29 46 45]
[208 528 494]


In [ ]:
arr1 = np.array([16,24,26,10])
arr2 = np.array([13,22,19])
print(arr1+arr2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
# in which cases there will be no broadcasting error
# case 1 : when arrays are equal
# case 2 : if anyone of them is 1

arr1 = np.array([16,24,26])
arr2 = np.array([2])   # 2 2 2

print(arr1+arr2)

[18 26 28]


In [ ]:

# salary = np.array([25000, 40000, 55000, 70000, 30000, 90000])
# Replace salary with High if salary >=60000
# Replace salary with Medium if salary >=40000 and <=60000
# Otherwise Low

import numpy as np
salary = np.array([25000, 40000, 55000, 70000, 30000, 90000])
result = np.where(
    salary >= 60000, 'High',
    np.where(salary >= 4000, 'Medium','Low')
)

print(result)

['Medium' 'Medium' 'Medium' 'High' 'Medium' 'High']
